"""init schema

Revision ID: a7b064cb2024
Revises: 
Create Date: 2026-07-07 06:39:01.774579

"""
from alembic import op
import sqlalchemy as sa


revision = 'a7b064cb2024'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('BASIC_JOB_COMPETENCY', 'TECHNICAL_COMPETENCY', 'CHARACTER_WORK_ETHIC', 'HUMANITIES_LITERACY', 'FOREIGN_LANGUAGE', name='domain'), nullable=False),
    sa.Column('grade', sa.Enum('S', 'A', 'B', name='grade'), nullable=False),
    sa.Column('min_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('BASIC_JOB_COMPETENCY', 'TECHNICAL_COMPETENCY', 'CHARACTER_WORK_ETHIC', 'HUMANITIES_LITERACY', 'FOREIGN_LANGUAGE', name='domain'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('applicable_grade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'HOMEROOM_TEACHER', 'AREA_TEACHER', 'ADMIN', name='role'), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('class_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login_id'), 'users', ['login_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('BASIC_JOB_COMPETENCY', 'TECHNICAL_COMPETENCY', 'CHARACTER_WORK_ETHIC', 'HUMANITIES_LITERACY', 'FOREIGN_LANGUAGE', name='domain'), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('self_reported_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['scoring_criteria.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_table('ai_review_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('suggested_criterion_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('flag', sa.String(length=50), nullable=True),
    sa.Column('raw_model_output', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['suggested_criterion_id'], ['scoring_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_review_results_submission_id'), 'ai_review_results', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_review_results_submission_id'), table_name='ai_review_results')
    op.drop_table('ai_review_results')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_login_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('scoring_criteria')
    op.drop_table('grade_thresholds')
    # ### end Alembic commands ###
