"""google oauth onboarding, bulk grants, scoring crud, awarded score

Revision ID: c9dee6061ff0
Revises: e5d7549b114d
Create Date: 2026-07-08 01:55:59.968195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = 'c9dee6061ff0'
down_revision = 'e5d7549b114d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('BASIC_JOB_COMPETENCY', 'TECHNICAL_COMPETENCY', 'CHARACTER_WORK_ETHIC', 'HUMANITIES_LITERACY', 'FOREIGN_LANGUAGE', name='domain'), nullable=False),
    sa.Column('score_per_student', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['scoring_criteria.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulk_grant_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulk_grant_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bulk_grant_id'], ['bulk_grants.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_grant_targets_bulk_grant_id'), 'bulk_grant_targets', ['bulk_grant_id'], unique=False)
    op.add_column('scoring_criteria', sa.Column('owner_department', sa.String(length=50), nullable=True))
    op.add_column('submissions', sa.Column('awarded_score', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=False))
    op.add_column('users', sa.Column('student_no', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approvalstatus'), nullable=False))
    op.drop_index('ix_users_login_id', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'login_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('users', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_login_id', 'users', ['login_id'], unique=True)
    op.drop_column('users', 'approval_status')
    op.drop_column('users', 'department')
    op.drop_column('users', 'student_no')
    op.drop_column('users', 'email')
    op.drop_column('submissions', 'awarded_score')
    op.drop_column('scoring_criteria', 'owner_department')
    op.drop_index(op.f('ix_bulk_grant_targets_bulk_grant_id'), table_name='bulk_grant_targets')
    op.drop_table('bulk_grant_targets')
    op.drop_table('bulk_grants')
    # ### end Alembic commands ###
