"""add teacher domain assignment

Revision ID: e5d7549b114d
Revises: a7b064cb2024
Create Date: 2026-07-07 06:42:23.350421

"""
from alembic import op
import sqlalchemy as sa


revision = 'e5d7549b114d'
down_revision = 'a7b064cb2024'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_domain_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('BASIC_JOB_COMPETENCY', 'TECHNICAL_COMPETENCY', 'CHARACTER_WORK_ETHIC', 'HUMANITIES_LITERACY', 'FOREIGN_LANGUAGE', name='domain'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_domain_assignments_teacher_id'), 'teacher_domain_assignments', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_domain_assignments_teacher_id'), table_name='teacher_domain_assignments')
    op.drop_table('teacher_domain_assignments')
    # ### end Alembic commands ###
